export {default as AboutUs} from "./aboutUsPage"
export {default as DashBoard} from "./dashboard"
export {default as Login} from "./login"
export {default as Autocounter} from "./autocounter"
export {default as FormDialog} from "./formDialogue"
export {default as Register} from "./Register"
export {default as LoginPage} from "./LoginPage"
export {default as welcomePage} from "./welcomePage"
export {default as Form} from "./form"
export {default as Contact} from "./contact"

